apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  namespace: default
  labels:
    app: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-demo
        image: coolsahil500/argocd-demo-frontend:v20250715125112
        ports:
        - containerPort: 80