name: test-and-run

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Docker Setup
      uses: docker/setup-buildx-action@v2

    # Step 3: Login to DockerHub
    - name: Docker Credentials
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Generate version tag
    - name: Docker tag
      id: version
      run: |
        VERSION=v$(date +"%Y%m%d%H%M%S")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    # Step 5: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t coolsahil500/argocd-demo-frontend:${{ env.VERSION }} .

    # Step 6: Push Docker image to DockerHub
    - name: Push Docker Image
      run: |
        docker push coolsahil500/argocd-demo-frontend:${{ env.VERSION }}

    # Step 7: Update image version in Kubernetes manifest
    - name: Update K8s Manifest
      run: |
        sed -i "s|image: coolsahil500/argocd-demo-frontend:.*|image: coolsahil500/argocd-demo-frontend:${{ env.VERSION }}|g" deploy/deployment.yaml

    # Step 8: Commit updated manifest back to GitHub
    - name: Commit the changes
      run: |
        git config --global user.email "github-actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"

        git add deploy/deployment.yaml

        if git diff --cached --quiet; then
          echo "✅ No changes to commit."
        else
          git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
          git push origin main
        fi
